<?php
    include('partials/header.phtml');
    include('partials/progress.phtml')
?>
<div id="add_transaction">
    <div class="add_transaction__tabs">
        <span>Wydatki</span><span>Wpływy</span>
    </div>
    <form action="">
        <input type="number" name="amount" placeholder="Kwota">
        <label for="amount">PLN</label>
        <select class="add_transaction__category" name="category_id">

        </select>
        <input type="text" name="title" placeholder="Nazwa (opcjonalne)">
        <input type="hidden" name="cash_flow">
        <button type="submit">Dodaj</button>
    </form>
</div>
