<?php if ($user === null) : ?>
    <p>Hello | <a href="/login">Login</a> | <a href="/register">Register</a></p>
<?php endif; ?>

<h2>Add new post</h2>

<?php if ($this->session->has('error')) : ?>
    <div class="error-message">
        <p><?= $this->session->get('error') ?></p>
        <?php $this->session->remove('error') ?>
    </div>
<?php endif; ?>

<form method="post" action="/post/add">

    <?php if ($user === null) : ?>
    <div class="form-group">
        <label for="login">Login:</label>
        <input id="login" name="login" type="text">
    </div>
    <?php endif; ?>

    <div class="form-group">
        <label for="text">Text:</label>
        <textarea id="text" name="text"></textarea>
    </div>

    <div class="form-group">
        <button type="submit">Add post</button>
    </div>
</form>

<h2>Posts:</h2>
<div class="posts">
    <?php foreach ($posts as $post) : ?>
    <div class="post">
        <p class="post-author" style="display: inline-block"><?= $post->getAuthorLogin() ?></p>
        <p class="post-date" style="display: inline-block"><?= $post->getCreatedAt()->format('Y-m-d H:i') ?></p>
        <p class="post-text"><?= nl2br($post->getText()) ?></p>
    </div>
    <?php endforeach; ?>
</div>

<div class="post-pagination">
    <?php for ($i = 1; $i < $pages + 1; $i++) : ?>
    <a href="?page=<?= $i ?>"><?= $i ?></a>
    <?php endfor; ?>
</div>
