Hello world

<?php if ($user === null) : ?>
    <form method="post" action="/login">

        <div class="form-group">
            <label for="email">Email:</label>
            <input id="email" name="email" type="text">
        </div>

        <div class="form-group">
            <label for="password">Password:</label>
            <input id="password" name="password" type="password">
        </div>

        <div class="form-group">
            <button type="submit">Login</button>
        </div>
    </form>
    <p><a href="/register">Register</a></p>
<?php endif; ?>
