<?php
    $historia = [];//TODO podpiąć backend
    $historia_html = '';
    foreach ($historia as $h){
        $historia_html .= '<tr>';
        $historia_html .= '<td>'.$h['amount'].' PLN</td>';
        $historia_html .= '<td><div>'.$h['category_name'].'</div><div>'.$h['title'].'</div> </td>';
        $historia_html .= '</tr>';
    }
?>
<div id="dashboard">
    <h3>Oto historia Twoich transakcji</h3>
    <table>
        <tbody>
            <?php $historia_html?>
        </tbody>
    </table>
</div>