<?php
    $historia_html = '';
    foreach ($history as $transaction) {
        $historia_html .= '<tr>';
        $historia_html .= '<td>'.($transaction->getCashFlow() ? '+' : '-') . $transaction->getAmount().' PLN</td>';
        $historia_html .= '<td><div>'.$transaction->getCategory()->getName().'</div><div>'.$transaction->getTitle().'</div> </td>';
        $historia_html .= '</tr>';
    }
?>
<div id="dashboard">
    <h3>Oto historia Twoich transakcji</h3>
    <table>
        <tbody>
            <?= $historia_html?>
        </tbody>
    </table>
</div>
