<?php
include('partials/header.phtml');
?>
<div id="target">
    <form action="">
        <h3>Wpisz sumę, którą chcesz zaoszczędzić</h3>
        <input type="number" name="amount" placeholder="Kwota">
        <label for="amount">PLN</label>
<!--        TODO datepicker start end inputs-->
        <input type="hidden" name="start">
        <input type="hidden" name="end">
        <button type="submit">Zapisz</button>
    </form>
</div>
