<p>Hello | <a href="/">Go home</a> | <a href="/register">Register</a></p>

<?php if ($this->session->has('error')) : ?>
<div class="error-message">
    <p><?= $this->session->get('error') ?></p>
    <?php $this->session->remove('error') ?>
</div>
<?php endif; ?>

<form method="post" action="/login">

    <div class="form-group">
        <label for="email">Email:</label>
        <input id="email" name="email" type="text">
    </div>

    <div class="form-group">
        <label for="password">Password:</label>
        <input id="password" name="password" type="password">
    </div>

    <div class="form-group">
        <button type="submit">Login</button>
    </div>
</form>
