<p>Hello | <a href="/">Go home</a> | <a href="/login">Login</a></p>

<?php if ($this->session->has('error')) : ?>
<div class="error-message">
    <p><?= $this->session->get('error') ?></p>
    <?php $this->session->remove('error') ?>
</div>
<?php endif; ?>

<form method="post" action="/register">

    <div class="form-group">
        <label for="login">Login:</label>
        <input id="login" name="login" type="text">
    </div>

    <div class="form-group">
        <label for="password">Password:</label>
        <input id="password" name="password" type="password">
    </div>

    <div class="form-group">
        <label for="repeat_password">Repeat password:</label>
        <input id="repeat_password" name="repeat_password" type="password">
    </div>

    <div class="form-group">
        <button type="submit">Login</button>
    </div>
</form>
