<?php
    $target['amount'] = 1200.00;
    $target['date_str'] = 'PLN od 7.03.2017 do 7.04.2017';
?>
<header>
    <div class="user"><img src="" alt=""></div>
    <div class="target">
        <span>Cel oszczędzania</span>
        <div><?php echo($target['amount'])?></div>
        <div><?php echo($target['date_str'])?></div>
    </div>
    <div class="budget">
        <span>Budżet</span>
        <span><?php echo($budget)?></span>
        <span>PLN</span>
    </div>
</header>